version: "3"
services:
  npm:
    image: node:15-alpine
    entrypoint: npm
    volumes:
      - .:/home/alpine
    working_dir: /home/alpine

  app:
    build: ./docker/app
    tty: true
    volumes:
      - .:/home/alpine
    working_dir: /home/alpine
