version: "3"
services:
  npm:
    build: ./docker/node/18
    entrypoint: npm
    volumes:
      - .:/home/ubuntu/app
    working_dir: /home/ubuntu/app

  app:
    build: ./docker/node/18
    tty: true
    volumes:
      - .:/home/ubuntu/app
    working_dir: /home/ubuntu/app
